vendor: Kubernetes SIG-Architecture Conformance Sub Project
name: notkind
version: v0.9.0
website_url: https://apisnoop.cncf.io
repo_url: https://github.com/cncf/apisnoop
documentation_url: https://docs.apisnoop.io
product_logo_url: https://raw.githubusercontent.com/kubernetes-sigs/kind/master/logo/logo.svg
type: installer
description: testing submission of conformance results for kubekohn 2020 presentation
